### PR TITLE
Added functionality of searching by id

### PR DESCRIPTION
**Pull request by pavelapps**
Hello Franklin!
My name is Pavel. I've added functionality of searching in iTunes by id. Could you add this changes to main project, please.

### CODE REVIEW

**Comment by fvdm** [comment]
Hi Pavel,

Thank you, I'll check it out soon

**Comment by pavelapps** [comment]
Thank you too, man!
Your library very helped us to build Slack and Facebook bots!

**Comment by fvdm** [comment]
Cool!

I have just implemented the Lookup API without breaking the interface. Simply include the item ID in your params to get its object:

```js
searchitunes ({ id: 512939461 }, console.log);
```

These parameters trigger the Lookup API:

- amgAlbumId
- amgArtistId
- amgVideoId
- id
- isbn
- upc

**Comment by pavelapps** [comment]
Ok! Great!
Thanks.

**Comment by fvdm** [comment]
Alright I pushed v2.3.1 to npm, enjoy!

**Pull request closed without merging**
